name       : lshw
version    : '2.19'
release    : 5
source     :
    - https://github.com/lyonel/lshw/archive/refs/tags/B.02.19.tar.gz : 9a2809b07ad2a2d1c4ee115682e31e7b3116ed536ea70bef962cef1ca3d1553e
homepage   : https://ezix.org/project/wiki/HardwareLiSter
license    : GPL-2.0-or-later
summary    : lshw (List Hardware)
component  : system.utils
description: |
    lshw is a small tool to provide detailed information on the hardware configuration of the machine. It can report exact memory configuration, firmware version, mainboard configuration, CPU version and speed, cache configuration, bus speed, etc.
build      : |
    %make ZLIB=1
install    : |
    %make_install ZLIB=1
    # Use hwdata only
    rm -rf $installdir/usr/share/lshw
