name       : lshw
version    : 02.18
release    : 3
source     :
    - https://github.com/lyonel/lshw/archive/B.02.18.tar.gz : aa8cb2eebf36e9e46dfc227f24784aa8c87181ec96e57ee6c455da8a0ce4fa77
license    : GPL-2.0
summary    : lshw (List Hardware)
component  : system.utils
description: |
    lshw (List Hardware)
patterns   :
    - /usr/share/man
build      : |
    %make
install    : |
    %make_install
    # Use hwdata only
    rm -rf $installdir/usr/share/lshw
