name       : lshw
version    : 02.17
release    : 2
source     :
    - http://www.ezix.org/software/files/lshw-B.02.17.tar.gz : eb9cc053fa0f1e78685cb695596e73931bfb55d2377e3bc3b8b94aff4c5a489c
license    : GPL-2.0
summary    : lshw (List Hardware)
description: |
    lshw (List Hardware)
patterns   :
    - /usr/share/man
build      : |
    %make
install    : |
    %make_install
